# Generated by Django 4.0.10 on 2023-03-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_in', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_in', to='core.transaction', verbose_name='Transfer Deposit')),
                ('transaction_out', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_out', to='core.transaction', verbose_name='Transfer Withdraw')),
            ],
        ),
    ]
